openapi: 3.0.0
info:
  title: Goal Builder Notification API
  description: Goal Builder Notification API Spec
  version: '1.0'
servers:
  - url: http://financial-wellness-{env}.financial-wellness.{env}.int.dbk.ncr.com
    description: "GB Notification API's internal to Candescent"
    variables:
      env:
        default: dev
        enum:
          - dev
          - qal
          - pte
          - stg
          - prd

paths:
  /v1/goal-builder/notifications:
    get:
      tags:
        - Notifications
      operationId: GetNotifications
      summary: "Get Notifications"
      description: API For getting the Notifications
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/NotificationEntity"
        '400':
          $ref: "#/components/responses/400"
        '500':
          $ref: "#/components/responses/500"
    post:
      tags:
        - Notifications
      operationId: PostNotifications
      summary: "Create Notification"
      description: API For Creating the Notifications
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationEntity'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/NotificationEntity"
        '400':
          $ref: "#/components/responses/400"
        '500':
          $ref: "#/components/responses/500"

  /v1/goal-builder/notifications/{notificationId}:
    put:
      tags:
        - Notifications
      operationId: PutNotifications
      summary: "Update Notifications"
      description: API For updating the Notifications
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationEntity'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/NotificationEntity"
        '400':
          $ref: "#/components/responses/400"
        '500':
          $ref: "#/components/responses/500"

    delete:
      tags:
        - Notifications
      operationId: DeleteNotifications
      summary: "Delete Notifications"
      description: API For updating the Notifications
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - $ref: "#/components/parameters/authorization"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationEntity'
      responses:
        '204':
          description: Success
          headers:
            x-correlation-id:
              $ref: "#/components/headers/res-correlationId"
        '400':
          $ref: "#/components/responses/400"
        '500':
          $ref: "#/components/responses/500"

  /v1/goal-builder/notifications/batchProcess:
    post:
      tags:
        - Batch Operation
      operationId: Batch Operation
      summary: "Batch Operation"
      description: Internal Candescent API For processing the Batch Jobs (Start, Stop)
      parameters:
        - $ref: "#/components/parameters/correlationId"
        - name: operation
          in: query
          required: true
          schema:
            enum:
              - stopBatch
              - restartBatch
              - shutDownQuartzScheduler
              - startQuartzScheduler

      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  batch:
                    type: string
                    example: success
        '500':
          $ref: "#/components/responses/500"

# ------------------- Components ----------------

components:
  securitySchemes:
    auth:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    NotificationEntity:
      type: object
      properties:
        notificationId:
          type: string
          format: uuid
        institution:
          type: string
          example: "05523"
        institutionUser:
          type: string
          example: 84d5a0f1f12b419e9e990b2e383bd418
        email:
          type: string
          format: email
        phoneNumber:
          type: number
          minimum: 10
          maxLength: 10
          example: 408 XXX XXXX
        notificationCategory:
          type: string
          enum: [ON-TRACK,OFF-TRACK,WEEKLY,RESERVE-AMOUNT-NOTIFY]
        notificationSubscriptionConditions:
          type: array
          items:
            type: object
            properties:
              reserveBalanceThresholdLimit:
                type: number
                format: double
                example: 100
              goalThresholdLimit:
                type: number
                format: double
                example: 150

        notificationSubscriptionActions:
          type: object
          properties:
            emailAction:
              type: object
              properties:
                channel:
                  type: string
                  example: EMAIL
                active:
                  type: boolean
                  example: Y
                destination:
                  type: string
                  format: email
            pushAction:
              type: object
              properties:
                channel:
                  type: string
                  example: PUSH
                active:
                  type: boolean
                  example: Y
                destination:
                  type: string
                  example: CMA
            InAppAction:
              type: object
              properties:
                channel:
                  type: string
                  example: IN-APP
                active:
                  type: boolean
                  example: N
                destination:
                  type: string
                  example: CMA
    NotificationCategory:
      type: string
      enum:
        - ON-TRACK
        - OFF-TRACK
        - WEEKLY
        - RESERVE-AMOUNT-NOTIFY
    NotificationSubscriptionCondition:
      type: object
      properties:
        code:
          type: string
          example: threshold
        value:
          type: number
          example: 100
    NotificationSubscriptionActions:
      type: object
      properties:
        channel:
          type: string
          example: PUSH
        active:
          type: boolean
          example: Y
        destination:
          type: string
          example: CMA-CANDESCENT


    error:
      type: "object"
      properties:
        code:
          type: "string"
          description: "The error code"
          example: "GB-400-1001"
        message:
          type: "string"
          description: "The error message"
          example: "/query/notification must have required property 'notificationId' "
    errors:
      type: "object"
      properties:
        errors:
          type: "array"
          items:
            $ref: "#/components/schemas/error"

  parameters:
    correlationId:
      name: x-correlation-id
      in: header
      example: 07ae5002-4d4d-46d9-a6c6-bee9f9b29722
      schema:
        type: string
    authorization:
      name: Authorization
      in: header
      description: Signed JWT carrying user data
      required: false
      schema:
        type: string
        default: Bearer <JWT>

  headers:
    req-correlationId:
      description: Identifier for request
      required: false
      schema:
        type: string
        format: uuid
        default: d6d6aca7-8ac6-4339-8470-f4a0acc781b3
    res-correlationId:
      description: Identifier for response
      required: false
      schema:
        type: string
        format: uuid
        default: d6d6aca7-8ac6-4339-8470-f4a0acc781b3

  responses:
    400:
      description: "Bad Request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
          example:
            statusCode: 400
            error: ValidationException
            message: Client executed a bad request
            details: "/query/notification must have required property 'NotificationId' "
            displayMessage: Client executed a bad request
    500:
      description: "Internal Server Error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
          example:
            statusCode: 500
            error: ServerErrorException
            message: Server encountered a System Error
            details: Internal Server Error
            displayMessage: Server executed a system error